services:
  imotrack-frontend:
    image: ghcr.io/programmerdatch/imotrack-front-end:latest
    ports:
      - "7016:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
