import type { Metadata } from "next";
import { Josefin_Sans, Marcellus } from "next/font/google";
import "./globals.css";
import ClientLayout from "@/components/ClientLayout";
import QueryProvider from "@/components/QueryProvider";
import { Toaster } from "sonner";

const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  variable: "--font-josefin-sans",
  display: "swap",
});

const marcellus = Marcellus({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-marcellus",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Imotrak",
  description: "Generated by UR-TEKiNOVA HUB",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        {/* Load Leaflet CSS globally - ONLY ONCE */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.css"
          integrity="sha512-o9N1jHQtJt0h4xHgj1N1H5xQj7GEx1ENtzY3vMbqj4JqvM9K3oP0msqHyt1E1vOEq6CGiAt+rWS+3Dd5wUu5wQ=="
          crossOrigin=""
        />
      </head>
      <body className={`${josefinSans.variable} ${marcellus.variable} antialiased`}>
        <QueryProvider>
          <ClientLayout>{children}</ClientLayout>
        </QueryProvider>
        <Toaster />
      </body>
    </html>
  );
}